"""Hymnal Index Data - Gather"""

# Dictionary of hymn titles to numbers
# Entries are in the same order as the original hymnal index

hymns = {
    "A Celtic Rune": 664,
    "A Hymn of Glory Let Us Sing!": 545,
    "A Living Faith": 677,
    "A Mighty Fortress Is Our God": 687,
    "A Nuptial Blessing": 971,
    "A Place at the Table": 812,
    "A Voice Cries Out": 416,
    "Abundant Life": 811,
    "Ad Te Jesu Christe": 621,
    "Advent Alleluia": 411,
    "Advent Gathering Song": 405,
    "Again We Keep This Solemn Fast": 487,
    "All Are Welcome": 850,
    "All Creatures of Our God and King": 611,
    "All Glory Is Yours": 605,
    "All Glory, Laud, and Honor": 498,
    "All Hail the Power of Jesus' Name!": 570,
    "All People That on Earth Do Dwell": 853,
    "All that I am sings": 892,
    "All that I counted as gain": 792,
    "All That Is Hidden": 746,
    "All the Ends of the Earth": 604,
    "All the Ends of the Earth - Psalm 98": 70,
    "All Things New": 541,
    "All Who Hunger (Moore)": 925,
    "All Who Hunger, Gather Gladly (HOLY MANNA)": 852,
    "All Will Be Well": 693,
    "All You Works of God": 575,
    "Alleluia, Christ Is Risen": 518,
    "Alleluia! Give the Glory": 844,
    "Alleluia No. 1": 524,
    "Alleluia! Sing to Jesus!": 949,
    "Amazing Grace": 645,
    "Amazing grace (Goebel-Komala)": 684,
    "Amén. El Cuerpo de Cristo": 912,
    "America the Beautiful": 984,
    "Among All": 888,
    "And holy is your name": 102,
    "Angels, from the Realms of Glory": 438,
    "Angels We Have Heard on High": 430,
    "Anthem": 778,
    "As a Fire Is Meant for Burning": 744,
    "As We Gather at Your Table": 839,
    "As we journeyed on our way": 906,
    "As with Gladness Men of Old": 465,
    "Ashes": 962,
    "At Evening": 857,
    "At That First Eucharist": 914,
    "At the Cross Her Station Keeping": 488,
    "At the Lamb's High Feast We Sing": 536,
    "At the Name of Jesus": 569,
    "At the Table of Jesus": 948,
    "Ave María (Chant)": 887,
    "Ave María (Kantor)": 891,
    "Awake! Awake, and Greet the New Morn": 423,
    "Awake from your slumber": 766,
    "Awake to the Day": 399,
    "Away in a Manger": 448,
    "Baptized in Water": 903,
    "Be Joyful, Mary": 526,
    "Be Merciful, O Lord - Psalm 51 (Haugen)": 51,
    "Be Merciful, O Lord - Psalm 51 (Pishner)": 52,
    "Be Merciful, O Lord - Psalm 51 (Tate)": 54,
    "Be Not Afraid (Dufford)": 683,
    "Be Not Afraid (Taizé)": 516,
    "Be with Me - Psalm 91": 65,
    "Before the ending of the day": 22,
    "Behold the Lamb": 939,
    "Behold the Wood": 514,
    "Bless the Lord": 620,
    "Blessed are they who are poor in spirit": 592,
    "Blessed be God!": 900,
    "Blest Are They": 735,
    "Blest Are Those Who Love You - Psalm 128": 86,
    "Blest Are We": 789,
    "Blest Be the Lord": 686,
    "Boundless Love": 700,
    "Bread of Life, Cup of Blessing": 947,
    "Bread of Life from Heaven": 943,
    "Bring Forth the Kingdom": 734,
    "Build Us a Table": 754,
    "By the Waters of Babylon": 672,
    "Called by Christ": 767,
    "Canticle of Daniel - Daniel 3:57-88": 99,
    "Canticle of the Sun": 576,
    "Canticle of the Turning": 622,
    "Carol at the Manger": 443,
    "Center of My Life": 679,
    "Change Our Hearts": 493,
    "Child of Mercy": 431,
    "Chill of the nightfall": 452,
    "Christ Be in Your Senses": 896,
    "Christ, Be Our Light!": 590,
    "Christ Has No Body Now But Yours": 760,
    "Christ Has Promised to Be Present": 851,
    "Christ Has Risen": 530,
    "Christ is alive and goes before us": 522,
    "Christ Is Made the Sure Foundation": 745,
    "Christ Is Risen! Shout Hosanna!": 521,
    "Christ Is the King!": 571,
    "Christ the Lord Is Risen Today": 523,
    "City of God": 766,
    "Cold are the people": 442,
    "Come All You People": 849,
    "Come and Eat This Living Bread": 942,
    "Come and Fill Our Hearts": 637,
    "Come and Follow Me": 800,
    "Come and Journey with a Savior": 788,
    "Come and rest in the arms of God": 714,
    "Come back to me": 484,
    "Come, be my light": 800,
    "Come, come Emmanuel": 405,
    "Come, come to the banquet": 838,
    "Come Down, O Love Divine": 556,
    "Come, Holy Ghost": 559,
    "Come, Host of Heaven's High Dwelling Place": 846,
    "Come! Live in the light!": 807,
    "Come, Lord Jesus": 552,
    "Come, O God of all the earth": 577,
    "Come, O God, renew your people": 482,
    "Come, O Long-Expected Jesus": 403,
    "Come Now, Almighty King": 562,
    "Come now, the feast is spread": 739,
    "Come to Me (Bell)": 720,
    "Come to Me (Joncas)": 731,
    "Come to me, all you weary": 871,
    "Come to me, come to us": 842,
    "Come to Me, O Weary Traveler": 727,
    "Come to the Banquet": 931,
    "Come to the Feast (Haugen)": 585,
    "Come to the Feast": 838,
    "Come to the Water (Foley)": 584,
    "Come to the water": 899,
    "Come to Us": 842,
    "Come, You Faithful, Raise the Strain": 533,
    "Come, You Thankful People, Come": 634,
    "Comfort, Comfort, O My People": 413,
    "Comfort, My People": 396,
    "Coming Together for Wine and for Bread": 836,
    "Covenant Hymn": 904,
    "Creator of the Stars of Night": 420,
    "Crown Him with Many Crowns": 574,
    "Daniel 3:57-88: Canticle of Daniel": 99,
    "Dark is the night": 434,
    "Day Is Done": 858,
    "Deep Within": 486,
    "Deliver Us, O Lord of Truth": 750,
    "Diverse in Culture, Nation, Race": 833,
    "Do Not Let Your Hearts Be Troubled": 869,
    "Do you know what I have done": 506,
    "Don't Be Afraid": 719,
    "Don't be afraid, for I am with you": 711,
    "Dona Nobis Pacem": 822,
    "Draw Near": 935,
    "Dream a Dream": 425,
    "Dust and Ashes": 468,
    "Dwellers in the Holy City": 976,
    "Dwelling Place": 678,
    "Dying you destroyed our death": 974,
    "Each Winter As the Year Grows Older": 419,
    "Eagle's Wings": 691,
    "Earth, Earth, Awake!": 531,
    "Easter Alleluia": 537,
    "Eat This Bread": 941,
    "Emmaus": 906,
    "Emptied and humbled, obedient to death": 105,
    "Epiphany Carol": 462,
    "Even though the rain hides the stars": 710,
    "Every Nation on Earth - Psalm 72": 60,
    "Every nation sees the glory": 462,
    "Exodus 15: Song at the Sea": 95,
    "Exodus 15: Song of Moses": 96,
    "Eye Has Not Seen": 728,
    "Faith of our fathers": 677,
    "Faith, Hope and Love": 702,
    "Far beyond the reach of endless sky": 700,
    "Father, into Your Hands - Psalm 31": 43,
    "Father, We Thank You, Who Have Planted": 632,
    "Feed us and guide us": 489,
    "For All the Saints": 884,
    "For All the Saints Who've Shown Your Love": 885,
    "For Ever I Will Sing - Psalm 89": 64,
    "For everyone born, a place at the table": 812,
    "For God So Loved the World": 580,
    "For Living, for Dying": 927,
    "For the Beauty of the Earth": 633,
    "For the bread and wine": 631,
    "For the Faithful Who Have Answered": 883,
    "For the Healing of the Nations": 803,
    "For the Life of the World": 901,
    "For you, O Lord, my soul": 415,
    "For your sun that brightens the day": 608,
    "Forgive Our Sins": 965,
    "Forty Days and Forty Nights": 483,
    "Freedom Is Coming": 814,
    "Fresh as the Morning": 587,
    "From Ashes to the Living Font": 474,
    "Gather in Your Name": 936,
    "Gather Us In": 848,
    "Gather your people (Alonso)": 489,
    "Gather Your People (Hurd)": 837,
    "Gathered as One": 841,
    "Gift of Finest Wheat": 940,
    "Gift of God": 422,
    "Give Us Your Peace": 826,
    "Glória, Glória": 426,
    "Glory and Praise to Our God": 606,
    "Glory in the Cross": 501,
    "Go in Peace, Go in Love": 771,
    "Go Make a Difference": 775,
    "Go Make of All Disciples": 769,
    "Go Out to the World": 762,
    "Go Tell It on the Mountain": 428,
    "Go to the World!": 546,
    "God Has Chosen Me": 761,
    "God Is Forgiveness": 959,
    "God Is Here! As We His People": 843,
    "God Is Love": 699,
    "God is praised and exalted": 99,
    "God Is Still Speaking": 595,
    "God Mounts His Throne - Psalm 47": 50,
    "God of Adam, God of Joseph": 982,
    "God of All People": 412,
    "God of all places": 412,
    "God of Day and God of Darkness": 859,
    "God of Eve and God of Mary": 983,
    "God of the Bible": 587,
    "God Remembers": 669,
    "God Rest You Merry, Gentlemen": 435,
    "God Sends Us Forth": 759,
    "God Weeps with Us Who Weep and Mourn": 673,
    "God Will Wipe the Tears": 715,
    "God, in the Planning": 970,
    "God, Whose Purpose Is to Kindle": 813,
    "God, you have moved upon the waters": 661,
    "Good Christian Friends, Rejoice": 440,
    "Good News": 768,
    "Goodness Is Stronger than Evil": 528,
    "Gracious God of wisdom": 397,
    "Guide My Feet": 780,
    "Hail, Holy Queen Enthroned Above": 879,
    "Hail Mary, full of grace (Kantor)": 891,
    "Hail Mary, full of grace (Landry)": 889,
    "Hail Mary: Gentle Woman": 889,
    "Hail Our Savior's Glorious Body / Pange Lingua": 509,
    "Hail Our Savior's Glorious Body": 509,
    "Hail, Queen of Heaven / Salve, Regína": 880,
    "Hail, Queen of Heaven": 880,
    "Hail the Day That Sees Him Rise": 543,
    "Halleluya! We Sing Your Praises": 626,
    "Hands of Healing": 954,
    "Hark! The Herald Angels Sing": 424,
    "Have Mercy, Lord - Psalm 51": 53,
    "He Came Down": 429,
    "He Healed the Darkness of My Mind": 953,
    "Healer of Our Every Ill": 960,
    "Healing River": 643,
    "Healing River of the Spirit": 665,
    "Heart of a Shepherd": 786,
    "Heaven Is Singing for Joy": 599,
    "Here Am I": 804,
    "Here I Am - Psalm 40 (Alonso)": 48,
    "Here I Am - Psalm 40 (Cooney)": 49,
    "Here I Am, Lord": 777,
    "Here in the Bread that is broken": 907,
    "Here in this place": 848,
    "Hold Us in Your Mercy: Penitential Litany": 494,
    "Hold Us, Jesus": 652,
    "Holy and blessed Three": 561,
    "Holy child within the manger": 443,
    "Holy God": 629,
    "Holy God, We Praise Thy Name": 615,
    "Holy, Holy, Holy! Lord God Almighty!": 567,
    "Holy Is Your Name - Luke 1:46-55": 102,
    "Holy Spirit, Come to Us": 547,
    "Hosanna": 499,
    "Hosea": 484,
    "How Can I Keep from Singing?": 685,
    "How Can We Be Silent": 772,
    "How Firm a Foundation": 694,
    "How Good, Lord, to Be Here!": 877,
    "How Great Thou Art": 578,
    "How Shall We Name God?": 667,
    "How Wonderful the Three-in-One": 563,
    "I Am for You": 794,
    "I Am Sure I Shall See": 682,
    "I Am the Bread of Life": 945,
    "I am the hungry": 816,
    "I baptize you in the name of the Father": 758,
    "I Come with Joy": 919,
    "I Danced in the Morning": 796,
    "I fall on my knees": 678,
    "I Have Been Anointed": 718,
    "I have fixed my eyes": 492,
    "I Have Loved You": 588,
    "I Heard the Voice of Jesus Say": 724,
    "I Know That My Redeemer Lives! (DUKE STREET)": 527,
    "I Know That My Redeemer Lives (Haas)": 972,
    "I Know That My Redeemer Lives (Hughes)": 973,
    "I Lift My Soul to You": 659,
    "I Receive the Living God": 916,
    "I Say \"Yes,\" Lord": 676,
    "I Send You Out": 758,
    "I Sing a Maid": 458,
    "I, the Lord, of sea and sky": 777,
    "I Want to Walk as a Child of the Light": 593,
    "I Will Be the Vine": 872,
    "I Will Choose Christ": 802,
    "I will come to you in the silence": 721,
    "I Will Praise the Lord - Psalm 146": 93,
    "I Will Praise You, Lord - Psalm 30": 42,
    "I Will Praise Your Name - Psalm 145": 92,
    "I Will Sing a Song of Love": 603,
    "I will sing, I will sing to the God who sets me free": 96,
    "If I Have Been the Source of Pain": 957,
    "If Today You Hear God's Voice - Psalm 95": 66,
    "If You Believe and I Believe": 818,
    "If you lose your life": 787,
    "If you love me, feed my lambs": 786,
    "If you would follow me": 746,
    "Immaculate Mary": 886,
    "In a far-off place, Jesus comes to earth": 447,
    "In Christ There Is No East or West": 832,
    "In Every Age": 716,
    "In Manus Tuas, Pater": 513,
    "In Paradísum / May Choirs of Angels": 977,
    "In Paradísum": 977,
    "In Remembrance of You": 944,
    "In the Arms of God": 714,
    "In the Breaking of the Bread": 918,
    "In the Cross of Christ": 515,
    "In the Lord I'll Be Ever Thankful": 639,
    "Increase Our Faith": 655,
    "Infant Holy, Infant Lowly": 445,
    "Isaiah 12: With Joy You Shall Draw Water": 97,
    "Isaiah 12: You Will Draw Water Joyfully": 98,
    "It Came upon the Midnight Clear": 433,
    "Jerusalem, My Destiny": 492,
    "Jerusalem, My Happy Home": 870,
    "Jesu, Jesu": 505,
    "Jesus Christ Is Lord! - Philippians 2:6-11": 105,
    "Jesus Christ Is Risen Today": 540,
    "Jesus Christ, Yesterday, Today, and for Ever": 847,
    "Jesus Comes": 447,
    "Jesus, give us your peace": 826,
    "Jesus, Heal Us": 952,
    "Jesus, hope for all": 944,
    "Jesus, Hope of the World": 909,
    "Jesus in the Morning": 757,
    "Jesus Is Here Right Now": 934,
    "Jesus Is the Resurrection": 840,
    "Jesus, Lead the Way": 732,
    "Jesus, our teacher and our Lord": 507,
    "Jesus, Remember Me": 510,
    "Jesus, the living Bread of God": 921,
    "Jesus, the Lord": 491,
    "Jesus, Your Spirit in Us": 752,
    "Joy to the World": 437,
    "Joyful, Joyful, We Adore You": 614,
    "Joyous Cup": 929,
    "Jubiláte, Sérvite": 618,
    "Keep in Mind": 646,
    "Keep Me Safe, O God - Psalm 16": 29,
    "Kneeling in the garden grass": 495,
    "Kýrie (Browning)": 472,
    "Kýrie (Haugen)": 490,
    "Laudáte Dóminum": 623,
    "Laudáte, Laudáte Dóminum": 601,
    "Lead Me, Guide Me": 656,
    "Lead us from death to life": 827,
    "Let All Mortal Flesh Keep Silence": 619,
    "Let All the Earth - Psalm 66": 59,
    "Let All Things Now Living": 635,
    "Let Justice Roll Like a River": 810,
    "Let our hands be hands of healing": 954,
    "Let There Be Light": 561,
    "Let There Be Peace on Earth": 829,
    "Let Us Be Bread": 946,
    "Let us build a house": 850,
    "Let Us Go Rejoicing - Psalm 122": 84,
    "Let Us Rejoice - Psalm 118": 81,
    "Let your gentleness be known": 823,
    "Let Your Mercy Be on Us - Psalm 33": 44,
    "Life-Giving Bread, Saving Cup": 926,
    "Lift High the Cross": 881,
    "Lift Up Your Hearts": 624,
    "Like a Bird": 408,
    "Like a Shepherd": 402,
    "Litany of Mary": 890,
    "Living Spirit, Holy Fire": 549,
    "Lo, How a Rose E'er Blooming": 451,
    "Long before my journey's start": 583,
    "Long before the mountains came to be": 716,
    "Longing for light": 590,
    "Look to Christ": 779,
    "Lord, hear our prayer": 664,
    "Lord, I Lift Your Name on High": 602,
    "Lord, increase our faith": 655,
    "Lord Jesus Christ (Browning)": 477,
    "Lord Jesus Christ (Bertier)": 589,
    "Lord, Let Us See Your Kindness - Psalm 85": 62,
    "Lord, make us worthy": 662,
    "Lord of All Hopefulness": 663,
    "Lord of All Nations, Grant Me Grace": 703,
    "Lord, Send Out Your Spirit - Psalm 104 (Lisicky)": 76,
    "Lord, Send Out Your Spirit - Psalm 104 (Proulx)": 77,
    "Lord, Today": 464,
    "Lord, When You Came": 781,
    "Lord, Who at Your First Eucharist": 914,
    "Lord, Who throughout These Forty Days": 479,
    "Lord, Whose Love in Humble Service": 764,
    "Lord, You Give the Great Commission": 544,
    "Lord, You Have the Words - Psalm 19 (Alonso)": 32,
    "Lord, You Have the Words - Psalm 19 (Haas)": 31,
    "Lord, you lead through sea and desert": 799,
    "Love Divine, All Loves Excelling": 641,
    "Love Endures All Things": 698,
    "Love Has Brought Us Here Together": 969,
    "Love Is Never Ending - Psalm 136": 90,
    "Love Is the Sunlight": 967,
    "Luke 1:46-53: My Soul Gives Glory": 100,
    "Luke 1:46-55: Holy Is Your Name": 102,
    "Luke 1:46-55: Magníficat": 101,
    "Luke 1:68-79: Now Bless the God of Israel": 103,
    "Luke 2:29-34: Nunc Dimíttis": 104,
    "Magníficat (Haas)": 892,
    "Magníficat - Luke 1:46-55 (Chepponis)": 101,
    "Magníficat (Taizé)": 630,
    "Make Me a Channel of Your Peace": 828,
    "Make Us Turn to You": 958,
    "Make Us Worthy": 662,
    "Making Their Way": 845,
    "Many and Great": 911,
    "Many faces, the young and the old": 841,
    "Maranatha, Come": 410,
    "Maranatha, Lord Messiah": 397,
    "Mary, First among Believers": 893,
    "May Choirs of Angels / In Paradísum": 977,
    "May Choirs of Angels": 977,
    "May God Bless and Keep You": 675,
    "May God bless you": 971,
    "May Holy Angels Lead You": 978,
    "May the Angels Lead You into Paradise": 980,
    "May the Peace of Christ Be with You": 674,
    "May the Spirit of Christ": 793,
    "May We Be One (Communion Hymn)": 394,
    "May We Be One (Communion Litany)": 393,
    "May we find richness": 806,
    "Merciful God": 489,
    "Mercy, O God": 480,
    "Mine Eyes Have Seen the Glory": 985,
    "Morning Has Broken": 855,
    "My Country, 'Tis of Thee": 988,
    "My God, My God - Psalm 22": 33,
    "My life flows on in endless song": 685,
    "My shepherd is the Lord (O'Brien)": 723,
    "My Shepherd Is the Lord - Psalm 23": 34,
    "My Song Will Be for You Forever": 704,
    "My soul cries out": 622,
    "My Soul Gives Glory (Duncan)": 894,
    "My Soul Gives Glory - Luke 1:46-53 (Joncas)": 100,
    "My Soul in Stillness Waits": 415,
    "My Soul Is Still - Psalm 131": 89,
    "My Soul Is Thirsting - Psalm 63 (Joncas)": 55,
    "My Soul Is Thirsting - Psalm 63 (Proulx)": 56,
    "My Soul, Give Thanks to the Lord - Psalm 103": 73,
    "Nada Te Turbe / Nothing Can Trouble": 733,
    "Nada Te Turbe": 733,
    "Nativity Carol": 432,
    "Neither Death nor Life": 647,
    "Never Give Up": 755,
    "Night of Silence": 442,
    "No Greater Love": 701,
    "No Wind at the Window": 876,
    "Not for Tongues of Heaven's Angels": 709,
    "Nothing Can Ever": 697,
    "Nothing Can Trouble / Nada Te Turbe": 733,
    "Nothing Can Trouble": 733,
    "Nourish us well": 927,
    "Now Bless the God of Israel - Luke 1:68-79": 103,
    "Now in This Banquet": 937,
    "Now it is evening": 857,
    "Now Let Your Servant Go in Peace": 874,
    "Now, O Lord, dismiss your servants": 104,
    "Now Thank We All Our God": 636,
    "Now the Green Blade Rises": 534,
    "Now We Remain": 785,
    "Nunc Dimíttis - Luke 2:29-34": 104,
    "O beautiful for spacious skies": 984,
    "O Breathe on Me, O Breath of God": 902,
    "O Come, All Ye Faithful": 439,
    "O Come, Divine Messiah!": 401,
    "O Come, O Come, Emmanuel": 395,
    "O Freedom": 814,
    "O God, Almighty Father": 566,
    "O God beyond All Praising": 598,
    "O God of Every Nation": 825,
    "O God of Exodus": 648,
    "O God, Our Help in Ages Past": 688,
    "O God, This Is the People - Psalm 24": 37,
    "O God, Why Are You Silent?": 668,
    "O God, You Search Me": 581,
    "O Holy City, Seen of John": 863,
    "O Holy Spirit, by Whose Breath": 551,
    "O let all who thirst": 584,
    "O Little Town of Bethlehem": 446,
    "O Lord, Hear My Prayer": 666,
    "O Lord, I know you are near": 695,
    "O Lord my God, when I in awesome wonder": 578,
    "O Lord, the Guardian of My Heart": 654,
    "O Lord, you are the center of my life": 679,
    "O Most Holy One / O Sanctíssima": 895,
    "O Most Holy One": 895,
    "O radiant light": 13,
    "O Sacred Head Surrounded": 512,
    "O Sanctíssima / O Most Holy One": 895,
    "O Sanctíssima": 895,
    "O Sons and Daughters": 532,
    "O Spirit All-Embracing": 553,
    "O Taste and See": 917,
    "O the weary world is trudging": 864,
    "Of the Father's Love Begotten": 427,
    "Oh, everyone who thirsts": 585,
    "Oh, Look and Wonder": 831,
    "On Eagle's Wings": 691,
    "On Holy Ground": 809,
    "On Jordan's Bank": 418,
    "On That Day": 862,
    "On the Journey to Emmaus": 538,
    "Once in Royal David's City": 455,
    "One Bread, One Body": 932,
    "One Lord": 770,
    "Only This I Want": 782,
    "Only You, O God": 729,
    "Open My Eyes": 651,
    "Our Blessing-Cup - Psalm 116 (Alonso)": 79,
    "Our Blessing-Cup - Psalm 116 (Haugen)": 78,
    "Our Father, We Have Wandered": 956,
    "Our Help Comes from the Lord - Psalm 121": 83,
    "Out of the Depths - Psalm 130": 88,
    "Over My Head": 579,
    "Palm Sunday Processional": 496,
    "Pan de Vida": 920,
    "Pange Lingua / Hail Our Savior's Glorious Body": 509,
    "Pange Lingua": 509,
    "Parce Dómine": 473,
    "Peace, Be Not Anxious": 830,
    "Peace Be with Those": 975,
    "Peace before us, peace behind us": 821,
    "Peace Is Flowing Like a River": 819,
    "People, Look East": 409,
    "People of the Night": 407,
    "Philippians 2:6-11: Jesus Christ Is Lord!": 105,
    "Praise and Thanksgiving": 861,
    "Praise God in This Holy Dwelling - Psalm 150": 94,
    "Praise, My Soul, the King of Heaven": 613,
    "Praise Our God and Savior": 597,
    "Praise the God who changes places": 565,
    "Praise the One Who Breaks the Darkness": 625,
    "Praise to the Lord, the Almighty": 616,
    "Praise to You, O Christ, Our Savior": 596,
    "Praise We the Lord This Day": 875,
    "Prayer of Peace": 821,
    "Precious Lord, Take My Hand": 955,
    "Prepare a Room for Me": 504,
    "Prepare! Prepare!": 398,
    "Prepare the Way of the Lord": 400,
    "Proclaim the greatness of God": 101,
    "Proclaim to All the Nations - Psalm 96": 67,
    "Psalm 15: They Who Do Justice": 28,
    "Psalm 16: Keep Me Safe, O God": 29,
    "Psalm 16: You Will Show Me the Path of Life": 30,
    "Psalm 19: Lord, You Have the Words": 31,
    "Psalm 19: Words of Everlasting Life": 32,
    "Psalm 22: My God, My God": 33,
    "Psalm 23: My Shepherd Is the Lord": 34,
    "Psalm 23: Shepherd Me, O God": 35,
    "Psalm 23: The Lord Is My Shepherd": 36,
    "Psalm 24: We Long to See Your Face": 37,
    "Psalm 25: Remember Your Mercies": 38,
    "Psalm 25: To You, O Lord (Haugen)": 39,
    "Psalm 25: To You, O Lord (Pishner)": 40,
    "Psalm 27: The Lord Is My Light": 41,
    "Psalm 30: I Will Praise You, Lord": 42,
    "Psalm 31: Father, into Your Hands": 43,
    "Psalm 33: Let Your Mercy Be on Us": 44,
    "Psalm 34: Taste and See (Haugen)": 45,
    "Psalm 34: Taste and See (Guimont)": 46,
    "Psalm 34: The Cry of the Poor": 47,
    "Psalm 40: Here I Am (Alonso)": 48,
    "Psalm 40: Here I Am (Cooney)": 49,
    "Psalm 47: God Mounts His Throne": 50,
    "Psalm 51: Be Merciful, O Lord (Haugen)": 51,
    "Psalm 51: Be Merciful, O Lord (Pishner)": 52,
    "Psalm 51: Have Mercy, Lord": 53,
    "Psalm 63: My Soul Is Thirsting (Joncas)": 55,
    "Psalm 63: My Soul Is Thirsting (Proulx)": 56,
    "Psalm 63: My Soul Is Thirsting (Angrisano)": 57,
    "Psalm 63: Your Love Is Finer than Life": 58,
    "Psalm 66: Let All the Earth": 59,
    "Psalm 72: Every Nation on Earth": 60,
    "Psalm 84: How Lovely Is Your Dwelling Place": 61,
    "Psalm 85: Lord, Let Us See Your Kindness": 62,
    "Psalm 88: Day and Night": 63,
    "Psalm 89: For Ever I Will Sing": 64,
    "Psalm 91: Be with Me": 65,
    "Psalm 95: If Today You Hear God's Voice": 33,
    "Psalm 96: Proclaim to All the Nations": 67,
    "Psalm 96: Today Is Born Our Savior (Hughes)": 68,
    "Psalm 96: Today Is Born Our Savior (Krisman)": 69,
    "Psalm 98: All the Ends of the Earth": 70,
    "Psalm 100: We Are God's People": 71,
    "Psalm 103: My Soul, Give Thanks to the Lord": 73,
    "Psalm 103: The Lord Is Kind and Merciful (Cotter)": 72,
    "Psalm 103: The Lord Is Kind and Merciful (Haugen)": 75,
    "Psalm 103: The Lord Is Kind and Merciful (Alonso)": 74,
    "Psalm 104: Lord, Send Out Your Spirit (Lisicky)": 76,
    "Psalm 104: Lord, Send Out Your Spirit (Proulx)": 77,
    "Psalm 116: Our Blessing-Cup (Haugen)": 78,
    "Psalm 116: Our Blessing-Cup (Alonso)": 79,
    "Psalm 116: The Name of God": 80,
    "Psalm 118: Let Us Rejoice": 81,
    "Psalm 118: This Is the Day": 82,
    "Psalm 121: Our Help Comes from the Lord": 83,
    "Psalm 122: Let Us Go Rejoicing (Joncas)": 84,
    "Psalm 122: Let Us Go Rejoicing (Roberts)": 85,
    "Psalm 128: Blest Are Those Who Love You": 86,
    "Psalm 130: Out of the Depths": 88,
    "Psalm 130: With the Lord There Is Mercy": 87,
    "Psalm 131: My Soul Is Still": 89,
    "Psalm 136: Love Is Never Ending": 90,
    "Psalm 138: The Fragrance of Christ": 91,
    "Psalm 145: I Will Praise Your Name": 92,
    "Psalm 146: I Will Praise the Lord": 93,
    "Psalm 150: Praise God in This Holy Dwelling": 94,
    "Psalm of Hope": 684,
    "Put Peace into Each Other's Hands": 824,
    "Quietly, Peacefully": 713,
    "Rain Down": 582,
    "Rejoice, the Lord Is King!": 568,
    "Remember You Are Dust": 469,
    "Remember Your Love": 961,
    "Remember Your Mercies - Psalm 25": 38,
    "Rest Now in Me": 711,
    "Resucitó": 535,
    "Return to God": 478,
    "Return to the Lord": 471,
    "Ride On, Jesus, Ride": 497,
    "Rise Up, Shepherd, and Follow": 453,
    "Salve, Regína / Hail, Queen of Heaven": 880,
    "Salve, Regína": 880,
    "Savior of the Nations, Come": 421,
    "Seek Ye First": 658,
    "Send Down the Fire": 557,
    "Send Me, Jesus": 776,
    "Send Us Your Spirit": 552,
    "Sequence for Easter": 1065,
    "Sequence for Pentecost": 1084,
    "Set Your Heart on the Higher Gifts": 708,
    "Shall Tribulation or Distress": 649,
    "Shall We Gather at the River": 873,
    "Shelter Me, O God": 717,
    "Shepherd Me, O God - Psalm 23": 35,
    "Shepherd of My Heart": 723,
    "Shepherd of Souls": 910,
    "Sign us with ashes": 489,
    "Silent Night": 441,
    "Silent, in the chill of midnight": 432,
    "Sing a New Church": 743,
    "Sing a new song (Cooney)": 541,
    "Sing a New Song (Schutte)": 607,
    "Sing a New Song to the Lord": 627,
    "Sing Alleluia": 434,
    "Sing of Mary, Pure and Lowly": 457,
    "Sing of the Lord's Goodness": 610,
    "Sing Out, Earth and Skies!": 577,
    "Sing Praise to God": 600,
    "Sing to the Mountains": 519,
    "Sing with All the Saints in Glory": 539,
    "Sing your joy, proclaim God's glory!": 3,
    "Sitting with a child in sickness": 670,
    "Slaves and children, take a stand": 929,
    "So You Must Do": 507,
    "Softly and Tenderly Jesus Is Calling": 963,
    "Somebody's Knockin' at Your Door": 470,
    "Song at the Sea - Exodus 15": 95,
    "Song of Farewell": 974,
    "Song of Moses - Exodus 15": 96,
    "Song of St. Patrick": 793,
    "Song of the Body of Christ": 924,
    "Song of the Lord's Command": 506,
    "Song of the Lord's Supper": 508,
    "Song of the Stable": 452,
    "Song over the Waters": 661,
    "Songs of Thankfulness and Praise": 459,
    "Soon and Very Soon": 865,
    "Source and sovereign, rock and cloud": 667,
    "Spare us, gracious Lord": 473,
    "Spirit Blowing through Creation": 555,
    "Spirit of God": 554,
    "Spirit Wind": 560,
    "Stand Firm": 763,
    "Stand, O stand firm": 763,
    "Stand Up, Friends!": 565,
    "Star-Child": 449,
    "Stations of the Cross": 495,
    "Stay Here and Keep Watch": 502,
    "Steal Away to Jesus": 868,
    "Summoned by the God who made us": 743,
    "Surréxit Christus": 529,
    "Sweet Refreshment": 899,
    "Table Song": 923,
    "Take and Eat": 950,
    "Take and Eat This Bread": 928,
    "Take and Eat, This Is My Body": 908,
    "Take Me Home": 866,
    "Take my heart, O Lord": 650,
    "Take Up Your Cross (ERHALT UNS HERR)": 801,
    "Take Up Your Cross (Haas)": 787,
    "Take, O Take Me As I Am": 795,
    "Taste and See (Moore)": 930,
    "Taste and See - Psalm 34": 45,
    "That Easter Day with Joy Was Bright": 542,
    "The Aye Carol": 456,
    "The Call Is Clear and Simple": 707,
    "The Church of Christ": 765,
    "The Church's One Foundation": 742,
    "The Clouds' Veil": 710,
    "The Cross of Jesus": 482,
    "The Cry of the Poor - Psalm 34": 47,
    "The First Nowell": 460,
    "The Fragrance of Christ - Psalm 138": 91,
    "The Glory of These Forty Days": 481,
    "The God of All Eternity": 989,
    "The Hand of God Shall Hold You": 981,
    "The Harvest of Justice": 806,
    "The heavens are telling the glory of God": 576,
    "The heavens embrace the earth": 809,
    "The King of Glory": 572,
    "The King of Love My Shepherd Is": 712,
    "The King Shall Come When Morning Dawns": 414,
    "The Kingdom of God (LAUDATE DOMINUM)": 736,
    "The Kingdom of God (Taizé)": 740,
    "The Living Bread of God": 921,
    "The Lord Is Kind and Merciful - Psalm 103 (Cotter)": 72,
    "The Lord Is Kind and Merciful - Psalm 103 (Alonso)": 74,
    "The Lord Is Kind and Merciful - Psalm 103 (Haugen)": 75,
    "The Lord Is My Light (Bouknight)": 690,
    "The Lord Is My Light - Psalm 27 (Haas)": 41,
    "The Lord Is My Shepherd - Psalm 23": 36,
    "The Lord Is Near": 692,
    "The Lord Will Heal the Broken Heart": 730,
    "The Love of the Lord": 792,
    "The Master Came to Bring Good News": 964,
    "The Name of God - Psalm 116": 80,
    "The Peace of God": 823,
    "The Peace of the Earth": 820,
    "The People Who Walked in Darkness": 444,
    "The Play of the Godhead": 564,
    "The Reign of God": 738,
    "The Servant Song": 751,
    "The Strife Is O'er": 525,
    "The Summons": 790,
    "The Thirsty Cry for Water, Lord": 815,
    "The Trumpet in the Morning": 864,
    "The Virgin Mary Had a Baby Boy": 454,
    "There Are Many Rooms": 867,
    "There Is a Balm in Gilead": 640,
    "There Is a Longing": 653,
    "There is a mountain": 794,
    "There Is a Place": 979,
    "There is no greater love": 701,
    "There Is One Lord": 905,
    "There's a star in the east": 453,
    "There's a time for remembering": 979,
    "There's a Wideness in God's Mercy": 644,
    "These Alone Are Enough": 650,
    "They Who Do Justice - Psalm 15": 28,
    "They'll Know We Are Christians": 835,
    "This Day God Gives Me": 856,
    "This Is a Day of New Beginnings": 522,
    "This Is My Example": 503,
    "This Is My Song": 986,
    "This Is the Body of Christ": 951,
    "This Is the Day - Psalm 118": 82,
    "This Is the Feast of Victory": 520,
    "This Little Light of Mine": 591,
    "Those who were in the dark": 939,
    "Though the Mountains May Fall": 689,
    "'Tis the Gift to Be Simple": 748,
    "To bring glad tidings to the lowly": 773,
    "To Jesus Christ, Our Sovereign King": 573,
    "To you, O God": 605,
    "To You, O Lord - Psalm 25 (Haugen)": 39,
    "To You, O Lord - Psalm 25 (Pishner)": 40,
    "Today Is Born Our Savior - Psalm 96 (Hughes)": 68,
    "Today Is Born Our Savior - Psalm 96 (Krisman)": 69,
    "Touch the Earth Lightly": 805,
    "Transform Us": 878,
    "Tree of Life": 475,
    "Tú tienes, Señor": 32,
    "Turn away from sin": 469,
    "Turn My Heart, O God": 660,
    "Turn to the Living God": 485,
    "Two Fishermen": 798,
    "Ubi Cáritas (Hurd)": 696,
    "Ubi Cáritas (Taizé)": 500,
    "Ubi Cáritas / Where True Love and Charity Are Found (Chant)": 705,
    "Ubi Cáritas (Chant)": 705,
    "Unless a Grain of Wheat": 783,
    "Veni Creátor Spíritus": 558,
    "Veni Sancte Spíritus": 550,
    "Wade in the Water": 898,
    "Wait for the Lord": 406,
    "Warm the Time of Winter": 417,
    "Watch, O Lord": 860,
    "We Are Called": 807,
    "We are called, we are chosen": 778,
    "We Are God's People - Psalm 100": 71,
    "We Are Many Parts": 834,
    "We Are Marching": 594,
    "We Are One (de Silva)": 913,
    "We Are One (Wright)": 548,
    "We are one in the Spirit": 835,
    "We are the body of Christ (Haas)": 923,
    "We Are the Body of Christ (Cortez)": 741,
    "We Are the Light of the World": 592,
    "We are your people of the night": 407,
    "We Arise": 854,
    "We Await with Wakeful Care": 670,
    "We Cannot Measure How You Heal": 657,
    "We cannot own the sunlit sky": 811,
    "We come to share our story": 924,
    "We Come to Your Feast": 938,
    "We Come with Joy": 808,
    "We Gather Together": 638,
    "We Give You Thanks": 631,
    "We Have a Dream": 987,
    "We Have Been Told": 784,
    "We hold the death of the Lord": 785,
    "We Long to See Your Face - Psalm 24": 37,
    "We place upon your table": 938,
    "We Praise You (Dameans)": 617,
    "We Praise You (Haas)": 608,
    "We Remember": 681,
    "We remember one who loved us well": 508,
    "We rise again from ashes": 962,
    "We Shall Overcome": 817,
    "We Shall Rise Again": 871,
    "We should glory in the cross": 501,
    "We Three Kings of Orient Are": 463,
    "We Walk by Faith": 680,
    "We Walk His Way": 517,
    "We Will Serve the Lord": 753,
    "We Will Walk with God": 737,
    "Wealth can be an idol": 753,
    "Were I the Perfect Child of God": 791,
    "Were You There": 511,
    "What Child Is This": 466,
    "What Star Is This": 461,
    "What Wondrous Love Is This": 642,
    "What You Have Done for Me": 816,
    "Whatever Be the Love": 747,
    "When a star is shining": 450,
    "When I'm feeling all alone": 722,
    "When in Our Music God Is Glorified": 612,
    "When Jesus worked here on earth": 768,
    "When John Baptized by Jordan's River": 467,
    "When Love Is Found": 966,
    "When the King Shall Come Again": 404,
    "When the wind of winter blows": 417,
    "When they heard that Jesus was coming": 496,
    "When two or more gather": 936,
    "When We Are Living": 756,
    "Where Charity and Love Prevail": 706,
    "Where the Promise Shines": 450,
    "Where True Love and Charity Are Found / Ubi Cáritas": 705,
    "Where True Love and Charity Are Found": 705,
    "Where Two or Three Are Gathered": 907,
    "Where Your Treasure Is": 749,
    "Wherever You Go": 968,
    "Wherever you go, I will follow": 904,
    "Who Calls You by Name": 900,
    "Who is the baby": 456,
    "Why Stand So Far Away": 671,
    "Will you come and follow me": 790,
    "Will you let me be your servant": 751,
    "Wisdom, My Road": 583,
    "With a Shepherd's Care": 725,
    "With hands of justice and faith": 762,
    "With Joy You Shall Draw Water - Isaiah 12": 97,
    "With the Lord There Is Mercy - Psalm 130": 87,
    "With This Bread": 933,
    "With You by My Side": 722,
    "Within the Reign of God": 739,
    "Without Seeing You": 922,
    "Wood of the Cradle": 436,
    "Words of Everlasting Life - Psalm 19": 32,
    "World Peace Prayer": 827,
    "Ye Watchers and Ye Holy Ones": 882,
    "You are salt for the earth": 734,
    "You Are All I Want": 726,
    "You Are All We Have": 586,
    "You Are Called to Tell the Story": 774,
    "You Are Mine": 721,
    "You Are Near": 695,
    "You Are Strong, You Are Holy": 799,
    "You Are the Voice": 609,
    "You Have Anointed Me": 773,
    "You Have Been Enlightened": 897,
    "You Satisfy the Hungry Heart": 940,
    "You shall cross the barren desert": 683,
    "You Walk along Our Shoreline": 797,
    "You who dwell in the shelter of the Lord": 691,
    "You Will Draw Water Joyfully - Isaiah 12": 98,
    "You Will Show Me the Path of Life - Psalm 16": 30,
    "You, Lord, Are Both Lamb and Shepherd": 628,
    "Your Love Is Finer Than Life - Psalm 63": 58,
}


def get_hymn_number(title):
    """Get hymn number by exact title match."""
    return hymns.get(title)


def search_hymns(search_term, case_sensitive=False):
    """Search for hymns by partial title match.
    
    Args:
        search_term: Text to search for in hymn titles
        case_sensitive: Whether search should be case-sensitive
    
    Returns:
        dict: Dictionary of matching hymn titles and numbers
    """
    if case_sensitive:
        return {title: num for title, num in hymns.items()
                if search_term in title}
    else:
        search_lower = search_term.lower()
        return {title: num for title, num in hymns.items()
                if search_lower in title.lower()}


def get_all_hymns():
    """Get complete dictionary of all hymns."""
    return hymns.copy()


def count_hymns():
    """Get total number of hymns in index."""
    return len(hymns)


def keyify(string: str):
    """Convert human-readable titlecase to lowercase hyphen-separated string."""
    # Remove notes, if any
    if "|" in string:
        string = string.split("|")[0].strip()
    # Remove punctuation and special characters
    string = re.sub(r'[^a-zA-Z0-9]', ' ', string).strip().lower()
    return '-'.join(string.split())


# Export main symbols
__all__ = ["hymns", "get_hymn_number", "search_hymns", "get_all_hymns", "count_hymns"]
