"""Hymnal Index - Auto-generated"""

hymns = {
    '949 Alleluia! Sing to Jesus!': 1,
    'M a g n í f i c a t – L u k e': 1,
    ':': 1,
    'Sing your joy, proclaim God’s glory!': 3,
    '(Chepponis)': 5,
    '–': 6,
    '880 Salve, Regína / Hail, Queen of Heaven': 12,
    '87 With the Lord There Is Mercy – Psalm': 12,
    'O radiant light': 13,
    '974 Song of Farewell': 15,
    '793 Song of St. Patrick': 15,
    '835 They’ll Know We Are Christians': 15,
    '496 Palm Sunday Processional': 19,
    '827 World Peace Prayer': 19,
    '685 My life flows on in endless song': 22,
    '906 Emmaus': 23,
    '704 My Song Will Be for You Forever': 23,
    '723 Shepherd of My Heart': 23,
    '692 The Lord Is Near': 23,
    '668 O God, Why Are You Silent?': 24,
    '938 We place upon your table': 24,
    '(Haugen)': 25,
    '(Pishner)': 25,
    '711 Rest Now in Me': 25,
    '(Haas)': 27,
    'They Who Do Justice – Psalm': 28,
    'Keep Me Safe, O God – Psalm': 29,
    'Psalm 16: Keep Me Safe, O God': 29,
    '92 I Will Praise Your Name – Psalm': 30,
    'Lord, You Have the Words – Psalm': 31,
    '32 Palabras de Vida Eterna – Psalm': 31,
    'Psalm 19: Lord, You Have the Words': 31,
    'Tú tienes, Señor': 32,
    'Words of Everlasting Life – Psalm': 32,
    'My God, My God – Psalm': 33,
    'Psalm 22: My God, My God': 33,
    '1065 Sequence for Easter': 33,
    'My Shepherd Is the Lord – Psalm': 34,
    'Psalm 23: My Shepherd Is the Lord': 34,
    '915 Taste and See / Gusten y Vean': 34,
    '460 The First Nowell': 34,
    'Psalm 23: Shepherd Me, O God': 35,
    'Shepherd Me, O God – Psalm': 35,
    'The Lord Is My Shepherd – Psalm': 36,
    'O God, This Is the People – Psalm': 37,
    'Psalm 24: We Long to See Your Face': 37,
    'We Long to See Your Face – Psalm': 37,
    'Psalm 25: Remember Your Mercies': 38,
    'Remember Your Mercies – Psalm': 38,
    'Psalm 25: To You, O Lord (Haugen)': 39,
    '(Cooney)': 40,
    'Psalm 25: To You, O Lord (Pishner)': 40,
    'To You, O Lord – Psalm': 40,
    'Psalm 27: The Lord Is My Light': 41,
    'The Lord Is My Light – Psalm': 41,
    'Psalm 30: I Will Praise You, Lord': 42,
    'Father, into Your Hands – Psalm': 43,
    'Padre, a Tus Manos – Psalm': 43,
    'Let Your Mercy Be on Us – Psalm': 44,
    'Señor, Que Tu Misericordia – Psalm': 44,
    'Psalm 34: Taste and See (Haugen)': 45,
    'Taste and See – Psalm': 45,
    'Psalm 34: Taste and See (Guimont)': 46,
    '982 God of Adam, God of Joseph': 47,
    'Psalm 34: The Cry of the Poor': 47,
    'The Cry of the Poor – Psalm': 47,
    'Psalm 40: Here I Am (Alonso)': 48,
    'Here I Am – Psalm': 49,
    'Psalm 40: Here I Am (Cooney)': 49,
    'God Mounts His Throne – Psalm': 50,
    'Psalm 47: God Mounts His Throne': 50,
    '(Tate)': 51,
    '429 He Came Down': 51,
    '855 Morning Has Broken': 51,
    'Have Mercy, Lord – Psalm': 53,
    'Psalm 51: Have Mercy, Lord': 53,
    'Be Merciful, O Lord – Psalm': 54,
    'Misericordia, Señor – Psalm': 54,
    'My Soul Is Thirsting – Psalm': 56,
    'Psalm 63: Your Love Is Finer than Life': 58,
    'Your Love Is Finer Than Life – Psalm': 58,
    'Let All the Earth – Psalm': 59,
    'Psalm 66: Let All the Earth': 59,
    'Every Nation on Earth – Psalm': 60,
    'Psalm 72: Every Nation on Earth': 60,
    '(Proulx)': 63,
    '(Joncas)': 63,
    'Psalm 88: Day and Night': 63,
    'For Ever I Will Sing – Psalm': 64,
    'Psalm 89: For Ever I Will Sing': 64,
    'Be with Me – Psalm': 65,
    'Psalm 91: Be with Me': 65,
    '635 Let All Things Now Living': 66,
    'Proclaim to All the Nations – Psalm': 67,
    'Psalm 96: Proclaim to All the Nations': 67,
    'Psalm 96: Today Is Born Our Savior': 68,
    'Today Is Born Our Savior – Psalm': 69,
    'All the Ends of the Earth – Psalm': 70,
    'Psalm 98: All the Ends of the Earth': 70,
    'Psalm 100: We Are God’s People': 71,
    'We Are God’s People – Psalm': 71,
    '462 Every nation sees the glory': 72,
    'El Señor Es Compasivo – Psalm': 74,
    'Lord, Send Out Your Spirit – Psalm': 77,
    'Our Blessing-Cup – Psalm': 78,
    'Psalm 116: Our Blessing-Cup': 78,
    'El Cáliz que Bendecimos – Psalm': 79,
    'Psalm 116: The Name of God': 80,
    'The Name of God – Psalm': 80,
    'Psalm 118: Let Us Rejoice': 81,
    'Psalm 118: This Is the Day': 82,
    'This Is the Day – Psalm': 82,
    'Let Us Go Rejoicing – Psalm': 84,
    '662 Lord, make us worthy': 85,
    'Psalm 130: Out of the Depths': 88,
    '812 For everyone born, a place at the table': 89,
    'My Soul Is Still – Psalm': 89,
    'Psalm 131: My Soul Is Still': 89,
    'Love Is Never Ending – Psalm': 90,
    'Psalm 136: Love Is Never Ending': 90,
    '22 Before the ending of the day': 91,
    'Psalm 138: The Fragrance of Christ': 91,
    'The Fragrance of Christ – Psalm': 91,
    'Psalm 145: I Will Praise Your Name': 92,
    'I Will Praise the Lord – Psalm': 93,
    'Psalm 146: I Will Praise the Lord': 93,
    'Exodus 15: Song at the Sea': 95,
    '818 If You Believe and I Believe': 95,
    'Song at the Sea – Exodus': 95,
    'Exodus 15: Song of Moses': 96,
    '924 Hoy venimos a contar': 96,
    '28 Psalm 15: They Who Do Justice': 96,
    'Song of Moses – Exodus': 96,
    '(Hughes)': 96,
    '(Krisman)': 96,
    '541 All Things New': 98,
    'Canticle of Daniel – Daniel 3:57–88': 99,
    'Daniel 3:57–88: Canticle of Daniel': 99,
    'God is praised and exalted': 99,
    'Luke 1:46–53: My Soul Gives Glory': 100,
    'Luke 1:46–55: Magníficat': 101,
    'Proclaim the greatness of God': 101,
    'And holy is your name': 102,
    'Holy Is Your Name – Luke 1:46-55': 102,
    'Luke 1:46–55: Holy Is Your Name': 102,
    '36 El Señor Es Mi Pastor – Psalm': 103,
    '(Alonso)': 103,
    '733 Nada Te Turbe / Nothing Can Trouble': 103,
    '(Cotter)': 103,
    '(Lisicky)': 104,
    'Luke 2:29–34: Nunc Dimíttis': 104,
    'Now, O Lord, dismiss your servants': 104,
    'Nunc Dimíttis – Luke 2:29–34': 104,
    '823 The Peace of God': 116,
    '823 Let your gentleness be known': 118,
    '520 This Is the Feast of Victory': 118,
    '88 Out of the Depths – Psalm': 121,
    '81 Let Us Rejoice – Psalm': 122,
    '579 Over My Head': 130,
    '55 My Soul Is Thirsting – Psalm': 131,
    '967 Love Is the Sunlight': 136,
    '481 The Glory of These Forty Days': 138,
    '603 I Will Sing a Song of Love': 145,
    '42 I Will Praise You, Lord – Psalm': 146,
    '613 Praise, My Soul, the King of Heaven': 150,
    'May We Be One (Communion Litany)': 393,
    'May We Be One (Communion Hymn)': 394,
    'O Come, O Come, Emmanuel': 395,
    'Comfort, My People': 396,
    'Gracious God of wisdom': 397,
    'Maranatha, Lord Messiah': 397,
    'Prepare! Prepare!': 398,
    'Awake to the Day': 399,
    'Prepare the Way of the Lord': 400,
    'O Come, Divine Messiah!': 401,
    'Like a Shepherd': 402,
    'Come, O Long-Expected Jesus': 403,
    'When the King Shall Come Again': 404,
    'Advent Gathering Song': 405,
    'Come, come Emmanuel': 405,
    'Wait for the Lord': 406,
    'People of the Night': 407,
    'We are your people of the night': 407,
    'Like a Bird': 408,
    'People, Look East': 409,
    'Maranatha, Come': 410,
    'Advent Alleluia': 411,
    'God of All People': 412,
    'God of all places': 412,
    'Comfort, Comfort, O My People': 413,
    'For you, O Lord, my soul': 415,
    'A V oice Cries Out': 416,
    'Warm the Time of Winter': 417,
    'When the wind of winter blows': 417,
    'On Jordan’s Bank': 418,
    'Each Winter As the Year Grows Older': 419,
    'Creator of the Stars of Night': 420,
    'Savior of the Nations, Come': 421,
    'Gift of God': 422,
    'Hark! The Herald Angels Sing': 424,
    'Dream a Dream': 425,
    'Glória, Glória': 426,
    'Of the Father’s Love Begotten': 427,
    'Go Tell It on the Mountain': 428,
    'Angels We Have Heard on High': 430,
    'Child of Mercy': 431,
    'Nativity Carol': 432,
    'Silent, in the chill of midnight': 432,
    'It Came upon the Midnight Clear': 433,
    'Dark is the night': 434,
    'Sing Alleluia': 434,
    'God Rest You Merry, Gentlemen': 435,
    'Wood of the Cradle': 436,
    'Joy to the World': 437,
    'Angels, from the Realms of Glory': 438,
    'Good Christian Friends, Rejoice': 440,
    'Noche de Paz / Silent Night': 441,
    'Silent Night / Noche de Paz': 441,
    'Cold are the people': 442,
    'Night of Silence': 442,
    'Carol at the Manger': 443,
    'Holy child within the manger': 443,
    'The People Who Walked in Darkness': 444,
    'Infant Holy, Infant Lowly': 445,
    'O Little Town of Bethlehem': 446,
    'In a far-off place, Jesus comes to earth': 447,
    'Jesus Comes': 447,
    'Away in a Manger': 448,
    'Star-Child': 449,
    'When a star is shining': 450,
    'Where the Promise Shines': 450,
    'Lo, How a Rose E’er Blooming': 451,
    'Chill of the nightfall': 452,
    'Song of the Stable': 452,
    'Rise Up, Shepherd, and Follow': 453,
    'There’s a star in the east': 453,
    'The Virgin Mary Had a Baby Boy': 454,
    'Once in Royal David’s City': 455,
    'The Aye Carol': 456,
    'Who is the baby': 456,
    'Sing of Mary, Pure and Lowly': 457,
    'I Sing a Maid': 458,
    'Songs of Thankfulness and Praise': 459,
    'What Star Is This': 461,
    'Epiphany Carol': 462,
    'We Three Kings of Orient Are': 463,
    'Lord, Today': 464,
    'As with Gladness Men of Old': 465,
    'What Child Is This': 466,
    'When John Baptized by Jordan’s River': 467,
    'Dust and Ashes': 468,
    'Remember You Are Dust': 469,
    'Turn away from sin': 469,
    'Somebody’s Knockin’ at Your Door': 470,
    'Return to the Lord': 471,
    'Kýrie (Browning)': 472,
    'Parce Dómine': 473,
    'Spare us, gracious Lord': 473,
    'From Ashes to the Living Font': 474,
    'Tree of Life': 475,
    'Adorámus Te Christe': 476,
    'Lord Jesus Christ': 477,
    'Mercy, O God': 480,
    'Come, O God, renew your people': 482,
    'The Cross of Jesus': 482,
    'Forty Days and Forty Nights': 483,
    'Come back to me': 484,
    'Hosea': 484,
    'Turn to the Living God': 485,
    'Deep Within': 486,
    'Again We Keep This Solemn Fast': 487,
    'At the Cross Her Station Keeping': 488,
    'Feed us and guide us': 489,
    'Gather your people (Alonso)': 489,
    'Merciful God': 489,
    'Sign us with ashes': 489,
    'Kýrie (Haugen)': 490,
    'Jesus, the Lord': 491,
    'I have fixed my eyes': 492,
    'Jerusalem, My Destiny': 492,
    'Change Our Hearts': 493,
    'Kneeling in the garden grass': 495,
    'Stations of the Cross': 495,
    'Ride On, Jesus, Ride': 497,
    'All Glory, Laud, and Honor': 498,
    'Hosanna': 499,
    'Ubi Cáritas (Taizé)': 500,
    'Glory in the Cross': 501,
    'We should glory in the cross': 501,
    'Stay Here and Keep Watch': 502,
    'This Is My Example': 503,
    'Prepare a Room for Me': 504,
    'Jesu, Jesu': 505,
    'Do you know what I have done': 506,
    'Song of the Lord’s Command': 506,
    'Jesus, our teacher and our Lord': 507,
    'So You Must Do': 507,
    'Song of the Lord’s Supper': 508,
    'We remember one who loved us well': 508,
    'Jesus, Remember Me': 510,
    'Were You There': 511,
    'In Manus Tuas, Pater': 513,
    'Behold the Wood': 514,
    'In the Cross of Christ': 515,
    'Be Not Afraid (Taizé)': 516,
    'Ewe, Thina / We Walk His Way': 517,
    'We Walk His Way / Ewe, Thina': 517,
    'Alleluia, Christ Is Risen': 518,
    'Sing to the Mountains': 519,
    'Christ Is Risen! Shout Hosanna!': 521,
    'Christ is alive and goes before us': 522,
    'This Is a Day of New Beginnings': 522,
    'Christ the Lord Is Risen Today': 523,
    'Alleluia No.': 524,
    'The Strife Is O’er': 525,
    'Be Joyful, Mary': 526,
    'Goodness Is Stronger than Evil': 528,
    'Surréxit Christus': 529,
    'Christ Has Risen': 530,
    'Earth, Earth, Awake!': 531,
    'O Sons and Daughters': 532,
    'Come, You Faithful, Raise the Strain': 533,
    'Now the Green Blade Rises': 534,
    'Resucitó': 535,
    'At the Lamb’s High Feast We Sing': 536,
    'Easter Alleluia': 537,
    'On the Journey to Emmaus': 538,
    'Jesus Christ Is Risen Today': 540,
    'Sing a new song (Cooney)': 541,
    'That Easter Day with Joy Was Bright': 542,
    'Hail the Day That Sees Him Rise': 543,
    'Lord, You Give the Great Commission': 544,
    'A Hymn of Glory Let Us Sing!': 545,
    'Go to the World!': 546,
    'Holy Spirit, Come to Us': 547,
    'We Are One (Wright)': 548,
    'Living Spirit, Holy Fire': 549,
    'Veni Sancte Spíritus': 550,
    'O Holy Spirit, by Whose Breath': 551,
    'Come, Lord Jesus': 552,
    'Send Us Your Spirit': 552,
    'O Spirit All-Embracing': 553,
    'Spirit of God': 554,
    'Spirit Blowing through Creation': 555,
    'Come Down, O Love Divine': 556,
    'Send Down the Fire': 557,
    'Veni Creátor Spíritus': 558,
    'Come, Holy Ghost': 559,
    'Spirit Wind': 560,
    'Holy and blessed Three': 561,
    'Let There Be Light': 561,
    'Come Now, Almighty King': 562,
    'How Wonderful the Three-in-One': 563,
    'The Play of the Godhead': 564,
    'Praise the God who changes places': 565,
    'Stand Up, Friends!': 565,
    'O God, Almighty Father': 566,
    'Holy, Holy, Holy! Lord God Almighty!': 567,
    'Rejoice, the Lord Is King!': 568,
    'At the Name of Jesus': 569,
    'All Hail the Power of Jesus’ Name!': 570,
    'Christ Is the King!': 571,
    'The King of Glory': 572,
    'To Jesus Christ, Our Sovereign King': 573,
    'Crown Him with Many Crowns': 574,
    'All You Works of God': 575,
    'Canticle of the Sun': 576,
    'Come, O God of all the earth': 577,
    'Sing Out, Earth and Skies!': 577,
    'How Great Thou Art': 578,
    'For God So Loved the World': 580,
    'O God, You Search Me': 581,
    'Rain Down': 582,
    'Long before my journey’s start': 583,
    'Wisdom, My Road': 583,
    'Come to the Water (Foley)': 584,
    'O let all who thirst': 584,
    'Come to the Feast': 585,
    'Oh, everyone who thirsts': 585,
    'You Are All We Have': 586,
    'Fresh as the Morning': 587,
    'God of the Bible': 587,
    'I Have Loved You': 588,
    'Jésus le Christ / Lord Jesus Christ': 589,
    'Lord Jesus Christ / Jésus le Christ': 589,
    'Christ, Be Our Light!': 590,
    'Longing for light': 590,
    'This Little Light of Mine': 591,
    'Blessed are they who are poor in spirit': 592,
    'We Are the Light of the World': 592,
    'I Want to Walk as a Child of the Light': 593,
    'Siyahamba / We Are Marching': 594,
    'We Are Marching / Siyahamba': 594,
    'God Is Still Speaking': 595,
    'Praise to You, O Christ, Our Savior': 596,
    'Praise Our God and Savior': 597,
    'O God beyond All Praising': 598,
    'Sing Praise to God': 600,
    'Laudáte, Laudáte Dóminum': 601,
    'Lord, I Lift Your Name on High': 602,
    'All the Ends of the Earth': 604,
    'All Glory Is Yours': 605,
    'To you, O God': 605,
    'Glory and Praise to Our God': 606,
    'Sing a New Song (Schutte)': 607,
    'For your sun that brightens the day': 608,
    'We Praise You (Haas)': 608,
    'You Are the V oice': 609,
    'All Creatures of Our God and King': 611,
    'When in Our Music God Is Glorified': 612,
    'Joyful, Joyful, We Adore You': 614,
    'Holy God, We Praise Thy Name': 615,
    'Praise to the Lord, the Almighty': 616,
    'We Praise You (Dameans)': 617,
    'Jubiláte, Sérvite': 618,
    'Let All Mortal Flesh Keep Silence': 619,
    'Bless the Lord': 620,
    'Ad Te Jesu Christe': 621,
    'Canticle of the Turning': 622,
    'My soul cries out': 622,
    'Laudáte Dóminum': 623,
    'Lift Up Your Hearts': 624,
    'Halleluya! We Sing Your Praises': 626,
    'Sing a New Song to the Lord': 627,
    'Holy God': 629,
    'Magníficat (Taizé)': 630,
    'For the bread and wine': 631,
    'We Give You Thanks': 631,
    'For the Beauty of the Earth': 633,
    'Come, You Thankful People, Come': 634,
    'Now Thank We All Our God': 636,
    'We Gather Together': 638,
    'In the Lord I’ll Be Ever Thankful': 639,
    'There Is a Balm in Gilead': 640,
    'Love Divine, All Loves Excelling': 641,
    'What Wondrous Love Is This': 642,
    'Healing River': 643,
    'There’s a Wideness in God’s Mercy': 644,
    'Amazing Grace': 645,
    'Keep in Mind': 646,
    'Neither Death nor Life': 647,
    'O God of Exodus': 648,
    'Shall Tribulation or Distress': 649,
    'Take my heart, O Lord': 650,
    'These Alone Are Enough': 650,
    'Open My Eyes': 651,
    'Hold Us, Jesus': 652,
    'There Is a Longing': 653,
    'O Lord, the Guardian of My Heart': 654,
    'Increase Our Faith': 655,
    'Lord, increase our faith': 655,
    'Lead Me, Guide Me': 656,
    'We Cannot Measure How You Heal': 657,
    'Seek Ye First': 658,
    'I Lift My Soul to You': 659,
    'Turn My Heart, O God': 660,
    'God, you have moved upon the waters': 661,
    'Song over the Waters': 661,
    'Lord of All Hopefulness': 663,
    'A Celtic Rune': 664,
    'Lord, hear our prayer': 664,
    'Healing River of the Spirit': 665,
    'O Lord, Hear My Prayer': 666,
    'How Shall We Name God?': 667,
    'Source and sovereign, rock and cloud': 667,
    'God Remembers': 669,
    'Sitting with a child in sickness': 670,
    'We Await with Wakeful Care': 670,
    'Why Stand So Far Away': 671,
    'By the Waters of Babylon': 672,
    'May God Bless and Keep You': 675,
    'Digo “Sí,” Señor / I Say “Yes,” Lord': 676,
    'I Say “Yes,” Lord / Digo “Sí,” Señor': 676,
    'A Living Faith': 677,
    'Faith of our fathers': 677,
    'Dwelling Place': 678,
    'I fall on my knees': 678,
    'Center of My Life': 679,
    'O Lord, you are the center of my life': 679,
    'We Walk by Faith': 680,
    'We Remember': 681,
    'I Am Sure I Shall See': 682,
    'Be Not Afraid (Dufford)': 683,
    'You shall cross the barren desert': 683,
    'Amazing grace (Goebel-Komala)': 684,
    'Psalm of Hope': 684,
    'How Can I Keep from Singing?': 685,
    'Blest Be the Lord': 686,
    'A Mighty Fortress Is Our God': 687,
    'O God, Our Help in Ages Past': 688,
    'Though the Mountains May Fall': 689,
    'The Lord Is My Light (Bouknight)': 690,
    'Eagle’s Wings': 691,
    'On Eagle’s Wings': 691,
    'All Will Be Well': 693,
    'How Firm a Foundation': 694,
    'O Lord, I know you are near': 695,
    'You Are Near': 695,
    'Ubi Cáritas (Hurd)': 696,
    'Nothing Can Ever': 697,
    'Love Endures All Things': 698,
    'God Is Love': 699,
    'Boundless Love / Tình Chúa Cao Vòi': 700,
    'Far beyond the reach of endless sky': 700,
    'Tình Chúa Cao Vòi / Boundless Love': 700,
    'No Greater Love': 701,
    'There is no greater love': 701,
    'Faith, Hope and Love': 702,
    'Lord of All Nations, Grant Me Grace': 703,
    'Where Charity and Love Prevail': 706,
    'The Call Is Clear and Simple': 707,
    'Set Your Heart on the Higher Gifts': 708,
    'Not for Tongues of Heaven’s Angels': 709,
    'Even though the rain hides the stars': 710,
    'The Clouds’ Veil': 710,
    'Don’t be afraid, for I am with you': 711,
    'The King of Love My Shepherd Is': 712,
    'Quietly, Peacefully': 713,
    'Come and rest in the arms of God': 714,
    'In the Arms of God': 714,
    'God Will Wipe the Tears': 715,
    'In Every Age': 716,
    'Long before the mountains came to be': 716,
    'Shelter Me, O God': 717,
    'I Have Been Anointed': 718,
    'Don’t Be Afraid': 719,
    'Come to Me (Bell)': 720,
    'Contigo Estoy / You Are Mine': 721,
    'I will come to you in the silence': 721,
    'You Are Mine / Contigo Estoy': 721,
    'With You by My Side': 722,
    'When I’m feeling all alone': 722,
    'My shepherd is the Lord (O’Brien)': 723,
    'I Heard the V oice of Jesus Say': 724,
    'With a Shepherd’s Care': 725,
    'You Are All I Want': 726,
    'Come to Me, O Weary Traveler': 727,
    'Eye Has Not Seen': 728,
    'Only You, O God': 729,
    'The Lord Will Heal the Broken Heart': 730,
    'Come to Me (Joncas)': 731,
    'Jesus, Lead the Way': 732,
    'Nothing Can Trouble / Nada Te Turbe': 733,
    'Bring Forth the Kingdom': 734,
    'You are salt for the earth': 734,
    'Benditos los Pobres / Blest Are They': 735,
    'Blest Are They / Benditos los Pobres': 735,
    'We Will Walk with God': 737,
    'The Reign of God': 738,
    'Come now, the feast is spread': 739,
    'Within the Reign of God': 739,
    'The Kingdom of God (Taizé)': 740,
    'The Church’s One Foundation': 742,
    'Sing a New Church': 743,
    'Summoned by the God who made us': 743,
    'As a Fire Is Meant for Burning': 744,
    'Christ Is Made the Sure Foundation': 745,
    'All That Is Hidden': 746,
    'If you would follow me': 746,
    'Whatever Be the Love': 747,
    '’Tis the Gift to Be Simple': 748,
    'Where Your Treasure Is': 749,
    'Deliver Us, O Lord of Truth': 750,
    'The Servant Song': 751,
    'Will you let me be your servant': 751,
    'Jesus, Your Spirit in Us': 752,
    'Wealth can be an idol': 753,
    'Build Us a Table': 754,
    'Bambelela / Never Give Up': 755,
    'Never Give Up / Bambelela': 755,
    'Pues Si Vivimos / When We Are Living': 756,
    'Jesus in the Morning': 757,
    'I baptize you in the name of the Father': 758,
    'I Send You Out': 758,
    'God Sends Us Forth': 759,
    'Christ Has No Body Now But Yours': 760,
    'God Has Chosen Me': 761,
    'Go Out to the World': 762,
    'Stand Firm': 763,
    'Stand, O stand firm': 763,
    'Lord, Whose Love in Humble Service': 764,
    'The Church of Christ': 765,
    'Awake from your slumber': 766,
    'City of God': 766,
    'Called by Christ': 767,
    'Good News': 768,
    'When Jesus worked here on earth': 768,
    'Go Make of All Disciples': 769,
    'One Lord': 770,
    'Go in Peace, Go in Love': 771,
    'How Can We Be Silent': 772,
    'To bring glad tidings to the lowly': 773,
    'You Have Anointed Me': 773,
    'You Are Called to Tell the Story': 774,
    'Go Make a Difference': 775,
    'Send Me, Jesus / Thuma Mina': 776,
    'Thuma Mina / Send Me, Jesus': 776,
    'Here I Am, Lord': 777,
    'I, the Lord, of sea and sky': 777,
    'Anthem': 778,
    'We are called, we are chosen': 778,
    'Look to Christ': 779,
    'Guide My Feet': 780,
    'Only This I Want': 782,
    'Unless a Grain of Wheat': 783,
    'We Have Been Told': 784,
    'Now We Remain': 785,
    'We hold the death of the Lord': 785,
    'If you love me, feed my lambs': 786,
    'Si me amas': 786,
    'If you lose your life': 787,
    'Take Up Your Cross (Haas)': 787,
    'Come and Journey with a Savior': 788,
    'Will you come and follow me': 790,
    'Were I the Perfect Child of God': 791,
    'All that I counted as gain': 792,
    'The Love of the Lord': 792,
    'May the Spirit of Christ': 793,
    'I Am for You': 794,
    'There is a mountain': 794,
    'Take, O Take Me As I Am': 795,
    'I Danced in the Morning': 796,
    'You Walk along Our Shoreline': 797,
    'Two Fishermen': 798,
    'Lord, you lead through sea and desert': 799,
    'You Are Strong, You Are Holy': 799,
    'Come and Follow Me': 800,
    'Come, be my light': 800,
    'I Will Choose Christ': 802,
    'For the Healing of the Nations': 803,
    'Touch the Earth Lightly': 805,
    'May we find richness': 806,
    'The Harvest of Justice': 806,
    'Come! Live in the light!': 807,
    'We Are Called': 807,
    'We Come with Joy': 808,
    'On Holy Ground': 809,
    'The heavens embrace the earth': 809,
    'Let Justice Roll Like a River': 810,
    'Abundant Life': 811,
    'We cannot own the sunlit sky': 811,
    'A Place at the Table': 812,
    'God, Whose Purpose Is to Kindle': 813,
    'Freedom Is Coming': 814,
    'O Freedom': 814,
    'The Thirsty Cry for Water, Lord': 815,
    'I am the hungry': 816,
    'What You Have Done for Me': 816,
    'We Shall Overcome': 817,
    'Peace Is Flowing Like a River': 819,
    'Peace before us, peace behind us': 821,
    'Prayer of Peace': 821,
    'Dona Nobis Pacem': 822,
    'Put Peace into Each Other’s Hands': 824,
    'O God of Every Nation': 825,
    'Give Us Your Peace': 826,
    'Jesus, give us your peace': 826,
    'Lead us from death to life': 827,
    'Make Me a Channel of Your Peace': 828,
    'Let There Be Peace on Earth': 829,
    'Peace, Be Not Anxious': 830,
    'In Christ There Is No East or West': 832,
    'Diverse in Culture, Nation, Race': 833,
    'We are one in the Spirit': 835,
    'Gather Your People (Hurd)': 837,
    'Come, come to the banquet': 838,
    'Come to the Feast / Ven al Banquete': 838,
    'Ven al Banquete / Come to the Feast': 838,
    'As We Gather at Your Table': 839,
    'Jesus Is the Resurrection': 840,
    'Gathered as One': 841,
    'Many faces, the young and the old': 841,
    'Come to me, come to us': 842,
    'Come to Us': 842,
    'God Is Here! As We His People': 843,
    'Alleluia! Give the Glory': 844,
    'Making Their Way': 845,
    'Gather Us In': 848,
    'Here in this place': 848,
    'Come All You People / Uyai Mose': 849,
    'Uyai Mose / Come All You People': 849,
    'All Are Welcome': 850,
    'Let us build a house': 850,
    'Christ Has Promised to Be Present': 851,
    'All People That on Earth Do Dwell': 853,
    'We Arise': 854,
    'This Day God Gives Me': 856,
    'At Evening': 857,
    'Now it is evening': 857,
    'Day Is Done': 858,
    'God of Day and God of Darkness': 859,
    'Watch, O Lord': 860,
    'Praise and Thanksgiving': 861,
    'On That Day': 862,
    'O Holy City, Seen of John': 863,
    'The Trumpet in the Morning': 864,
    'Soon and Very Soon': 865,
    'Take Me Home': 866,
    'There Are Many Rooms': 867,
    'Steal Away to Jesus': 868,
    'Do Not Let Your Hearts Be Troubled': 869,
    'Jerusalem, My Happy Home': 870,
    'Come to me, all you weary': 871,
    'We Shall Rise Again': 871,
    'I Will Be the Vine': 872,
    'Shall We Gather at the River': 873,
    'Now Let Your Servant Go in Peace': 874,
    'Praise We the Lord This Day': 875,
    'No Wind at the Window': 876,
    'How Good, Lord, to Be Here!': 877,
    'Transform Us': 878,
    'Hail, Holy Queen Enthroned Above': 879,
    'Hail, Queen of Heaven / Salve, Regína': 880,
    'Alcen la Cruz / Lift High the Cross': 881,
    'Lift High the Cross / Alcen la Cruz': 881,
    'Ye Watchers and Ye Holy Ones': 882,
    'For the Faithful Who Have Answered': 883,
    'For All the Saints': 884,
    'Immaculate Mary': 886,
    'Ave María (Chant)': 887,
    'Among All': 888,
    'Hail Mary, full of grace (Landry)': 889,
    'Hail Mary: Gentle Woman': 889,
    'Ave María (Kantor)': 891,
    'Hail Mary, full of grace (Kantor)': 891,
    'All that I am sings': 892,
    'Magníficat (Haas)': 892,
    'Mary, First among Believers': 893,
    'My Soul Gives Glory (Duncan)': 894,
    'O Most Holy One / O Sanctíssima': 895,
    'O Sanctíssima / O Most Holy One': 895,
    'Christ Be in Your Senses': 896,
    'You Have Been Enlightened': 897,
    'Wade in the Water': 898,
    'Come to the water': 899,
    'Sweet Refreshment': 899,
    'Blessed be God!': 900,
    'Who Calls You by Name': 900,
    'For the Life of the World': 901,
    'O Breathe on Me, O Breath of God': 902,
    'Baptized in Water': 903,
    'Covenant Hymn': 904,
    'Wherever you go, I will follow': 904,
    'There Is One Lord': 905,
    'As we journeyed on our way': 906,
    'Here in the Bread that is broken': 907,
    'Where Two or Three Are Gathered': 907,
    'Take and Eat, This Is My Body': 908,
    'Jesus, Hope of the World': 909,
    'Shepherd of Souls': 910,
    'Many and Great': 911,
    'Amén. El Cuerpo de Cristo': 912,
    'We Are One (de Silva)': 913,
    'Lord, Who at Your First Eucharist': 914,
    'Gusten y Vean / Taste and See': 915,
    'I Receive the Living God': 916,
    'O Taste and See': 917,
    'I Come with Joy': 919,
    'Pan de Vida': 920,
    'Jesus, the living Bread of God': 921,
    'The Living Bread of God': 921,
    'Without Seeing You': 922,
    'Table Song': 923,
    'We are the body of Christ (Haas)': 923,
    'We come to share our story': 924,
    'All Who Hunger (Moore)': 925,
    'Life-Giving Bread, Saving Cup': 926,
    'For Living, for Dying': 927,
    'Nourish us well': 927,
    'Take and Eat This Bread': 928,
    'Joyous Cup': 929,
    'Slaves and children, take a stand': 929,
    'Taste and See': 930,
    'Come to the Banquet': 931,
    'One Bread, One Body': 932,
    'With This Bread': 933,
    'Jesus Is Here Right Now': 934,
    'Draw Near': 935,
    'Gather in Your Name': 936,
    'When two or more gather': 936,
    'Now in This Banquet': 937,
    'We Come to Your Feast': 938,
    'Behold the Lamb': 939,
    'Those who were in the dark': 939,
    'Gift of Finest Wheat': 940,
    'You Satisfy the Hungry Heart': 940,
    'Eat This Bread': 941,
    'Come and Eat This Living Bread': 942,
    'In Remembrance of You': 944,
    'Jesus, hope for all': 944,
    'Let Us Be Bread': 946,
    'Bread of Life, Cup of Blessing': 947,
    'At the Table of Jesus': 948,
    'Take and Eat': 950,
    'This Is the Body of Christ': 951,
    'He Healed the Darkness of My Mind': 953,
    'Hands of Healing': 954,
    'Let our hands be hands of healing': 954,
    'Precious Lord, Take My Hand': 955,
    'Our Father, We Have Wandered': 956,
    'Make Us Turn to You': 958,
    'God Is Forgiveness': 959,
    'Healer of Our Every Ill': 960,
    'Remember Your Love': 961,
    'Ashes': 962,
    'We rise again from ashes': 962,
    'Softly and Tenderly Jesus Is Calling': 963,
    'The Master Came to Bring Good News': 964,
    'Forgive Our Sins': 965,
    'When Love Is Found': 966,
    'Wherever You Go': 968,
    'Love Has Brought Us Here Together': 969,
    'God, in the Planning': 970,
    'A Nuptial Blessing': 971,
    'May God bless you': 971,
    'Dying you destroyed our death': 974,
    'Peace Be with Those': 975,
    'Dwellers in the Holy City': 976,
    'In Paradísum / May Choirs of Angels': 977,
    'May Choirs of Angels / In Paradísum': 977,
    'May Holy Angels Lead You': 978,
    'There Is a Place': 979,
    'There’s a time for remembering': 979,
    'The Hand of God Shall Hold You': 981,
    'God of Eve and God of Mary': 983,
    'America the Beautiful': 984,
    'O beautiful for spacious skies': 984,
    'Mine Eyes Have Seen the Glory': 985,
    'This Is My Song': 986,
    'We Have a Dream': 987,
    'My Country, ’Tis of Thee': 988,
    'The God of All Eternity': 989,
    'Sequence for Pentecost': 1084,
    'G3 pew indexes (good).indd': 1087,
}

def get_hymn_number(title):
    """Get hymn number by title."""
    return hymns.get(title)

def search_hymns(search_term):
    """Search for hymns by partial title match."""
    search_lower = search_term.lower()
    return {title: num for title, num in hymns.items() 
            if search_lower in title.lower()}
